src/main/java/com/example/fighteam/teamspace/controller/TeamspaceController.java
src/main/java/com/example/fighteam/teamspace/controller/TeamspaceRestController.java
src/main/java/com/example/fighteam/teamspace/domain/dto/AttendanceCheckRequestDto.java
src/main/java/com/example/fighteam/teamspace/domain/dto/AttendanceResponseDto.java
src/main/java/com/example/fighteam/teamspace/domain/dto/AttendanceRowMapper.java
src/main/java/com/example/fighteam/teamspace/domain/dto/HistoryDto.java
src/main/java/com/example/fighteam/teamspace/domain/dto/RadioViewModel.java
src/main/java/com/example/fighteam/teamspace/domain/repository/Attendance.java
src/main/java/com/example/fighteam/teamspace/domain/repository/AttendanceRepository.java
src/main/java/com/example/fighteam/teamspace/domain/repository/Teamspace.java
src/main/java/com/example/fighteam/teamspace/domain/repository/TeamspaceRepository.java
src/main/java/com/example/fighteam/teamspace/service/TeamspaceService.java
src/main/resources/templates/AttendanceMain.html

Feature teamspace

---

src/main/java/com/example/fighteam/chat/controller/ChatController.java
src/main/java/com/example/fighteam/chat/controller/MessageController.java
src/main/java/com/example/fighteam/chat/service/ChatRoomService.java
src/main/resources/templates/chat/chat.html
src/main/resources/templates/chat/header.html

Chat Service View Header 추가 및 기본 들여쓰기

Feature.chatting

---

src/main/java/com/example/fighteam/teamspace/controller/TeamspaceController.java

TeamspaceMyPageResponseDto import

teamspace my page import

---

build.gradle
src/main/java/com/example/fighteam/chat/controller/ChatController.java
src/main/java/com/example/fighteam/chat/controller/MyPageController.java
src/main/java/com/example/fighteam/chat/domain/dto/MyPageDto.java
src/main/java/com/example/fighteam/chat/domain/repository/ChatMessage.java
src/main/java/com/example/fighteam/chat/domain/repository/ChatRoomRepository.java
src/main/java/com/example/fighteam/user/domain/repository/User.java
src/main/resources/templates/chat/chat.html
src/main/resources/templates/chat/chatList.html
src/main/resources/templates/chat/header.html
src/main/resources/templates/chat/mypageSide.html

Feat: 마이페이지 채팅방 내역

---

src/main/resources/templates/fragments/header.html

Chore.post header 수정

---

src/main/java/com/example/fighteam/chat/controller/ChatController.java
src/main/java/com/example/fighteam/chat/controller/MessageController.java
src/main/java/com/example/fighteam/chat/domain/dto/ChatMessageResponseDto.java
src/main/java/com/example/fighteam/chat/domain/repository/ChatRoomRepository.java
src/main/java/com/example/fighteam/chat/service/ChatMessageService.java
src/main/resources/templates/chat/chat.html

Post User가 자신의 글에서 채팅하기를 누를 시 mypageChat으로 return
이미 있는 채팅방일 시 바로 채팅방으로 들어감
메시지 user_id에서 user_name으로 보이게끔 수정

Feat: 채팅방 예외 처리 및 메시지 이름 수정

---

src/main/java/com/example/fighteam/payment/controller/HistoryController.java

결제내역 페이지 사이드바에서 클릭시 모든 정보 출력되도록 수정

Chore: 결제내역 페이지 default all로 수정

---

src/main/java/com/example/fighteam/post/domain/Post.java
src/main/java/com/example/fighteam/post/domain/repository/CommentJdbc.java
src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java
src/main/resources/templates/fragments/mypageSide.html
src/main/resources/templates/post/createpost.html
src/main/resources/templates/post/myboardcheckForm.html

Chore: 사이드바 createpost 수정

---

src/main/java/com/example/fighteam/apply/domain/repository/Apply.java
src/main/java/com/example/fighteam/payment/domain/Apply.java
src/main/java/com/example/fighteam/payment/service/PaymentService.java

Chore: Apply.status 타입 Boolean -> String 변경

---

src/main/java/com/example/fighteam/post/controller/PostController.java
src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java
src/main/resources/templates/post/createpost.html
src/main/resources/templates/post/fragment/table.html
src/main/resources/templates/post/postDetail.html

Chore.post 수정

---

src/main/java/com/example/fighteam/teamspace/service/TeamspaceService.java
src/main/resources/templates/teamspace/myPageTeamspace.html

status == null -> status == 'false'

Feat: status null -> status false

---

src/main/java/com/example/fighteam/post/controller/PostController.java
src/main/java/com/example/fighteam/post/domain/dto/GetCommentDto.java
src/main/java/com/example/fighteam/post/domain/repository/CommentJdbc.java
src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java
src/main/java/com/example/fighteam/post/domain/repository/PostRepository.java
src/main/java/com/example/fighteam/post/service/PostService.java
src/main/resources/templates/post/postDetail.html

Chore.comment 이름 수정

---

src/main/java/com/example/fighteam/chat/controller/MyPageController.java
src/main/resources/templates/chat/mypageSide.html

ChatRoom생성 후 아무 채팅 치지 않았을 때 채팅 내역 안들어가지는 버그 픽스

Fix: 채팅방 내역 버그 수정

---

src/main/resources/import.sql

Feat: Init insert sql 추가

---

src/main/java/com/example/fighteam/payment/controller/PaymentController.java
src/main/resources/templates/payment/member/payment/paymentPostResult.html

Chore: 결제 완료 게시글 작성, 지원하기 분리

---

src/main/resources/templates/payment/member/payment/paymentPostResult.html
src/main/resources/templates/payment/member/payment/paymentResult.html

Chore: 결제 완료페이지 버튼 수정

---

src/main/java/com/example/fighteam/apply/controller/ApplyController.java
src/main/java/com/example/fighteam/apply/domain/dto/ApplyResponseDto.java
src/main/java/com/example/fighteam/apply/service/ApplyService.java
src/main/java/com/example/fighteam/teamspace/controller/TeamspaceController.java
src/main/java/com/example/fighteam/teamspace/controller/TeamspaceRestController.java
src/main/java/com/example/fighteam/teamspace/domain/dto/AttendanceResponseDto.java
src/main/java/com/example/fighteam/teamspace/domain/dto/AttendanceRowMapper.java
src/main/java/com/example/fighteam/teamspace/service/TeamspaceService.java
src/main/resources/templates/teamspace/AttendanceMain.html
src/main/resources/templates/teamspace/CreateTeamspace.html
src/main/resources/templates/teamspace/ReviewTeammates.html

팀스페이스 에러, 출석 이벤트 에러, 팀스페이스 생성 에러 픽스

teamspace/attendance event/CreateTeamspace error fix

---

src/main/java/com/example/fighteam/post/domain/dto/GetPostDetailResponseDto.java
src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java
src/main/resources/templates/post/postDetail.html

Chore: 게시판 마감 수정

---

src/main/java/com/example/fighteam/teamspace/controller/TeamspaceController.java
src/main/resources/templates/teamspace/myPageTeamspace.html

myPageTeamspace, Teamspace controller modify

---

src/main/resources/templates/payment/member/charge/chargeForm2.html
src/main/resources/templates/payment/member/charge/chargeResult.html
src/main/resources/templates/payment/member/payment/paymentForm2.html
src/main/resources/templates/payment/member/payment/paymentPostForm.html
src/main/resources/templates/payment/member/payment/paymentPostResult.html
src/main/resources/templates/payment/member/payment/paymentResult.html

Chore: 타임리프 문법으로 인한 WARN 메시지 해결

Chore: 타임리프 문법으로 인한 WARN 메시지 해결

---

src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java

Feature post,comment

---

src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java

Chore: 게시판 수정

---

src/main/java/com/example/fighteam/apply/service/ApplyService.java

Chore: 신청 수락 버튼 오류 해결

---

src/main/java/com/example/fighteam/apply/service/ApplyService.java

Feature: 신청 수락 거절 구현

---

src/main/java/com/example/fighteam/post/domain/repository/PostJdbc.java

Chore: 게시판 모델수정

---

src/main/java/com/example/fighteam/user/controller/UserController.java
src/main/java/com/example/fighteam/user/domain/repository/UserRepository.java
src/main/java/com/example/fighteam/user/service/UserService.java
src/main/resources/templates/joinlogin/login.html
src/main/resources/templates/joinlogin/userEdit.html

Feat: 회원정보수정 진행중

---

src/main/java/com/example/fighteam/user/controller/UserController.java
src/main/resources/templates/joinlogin/join.html

Chore: 회원가입수정

---

src/main/java/com/example/fighteam/apply/service/ApplyService.java

Chore: 환불 금액 오류 수정

---

src/main/java/com/example/fighteam/post/domain/Post.java

Chore: 게시판내용 길이 수정

---

src/main/java/com/example/fighteam/payment/repository/ApplyRepository.java
src/main/java/com/example/fighteam/payment/service/PenaltyService.java

Feat: 프로젝트 종료후 보증금 반환 로직 구현

---

src/main/java/com/example/fighteam/payment/service/PenaltyService.java
src/main/java/com/example/fighteam/teamspace/service/TeamspaceService.java

Feature: 프로젝트 종료후 보증금 반환 로직 구현

Feature: 프로젝트 종료후 보증금 반환 로직 구현

---

src/main/java/com/example/fighteam/payment/repository/ApplyRepository.java
src/main/java/com/example/fighteam/payment/service/PenaltyService.java

Chore: 페널티 로직 수정
